apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin-daemon
  template:
    metadata:
      labels:
        app: plugin-daemon
    spec:
      containers:
        - name: plugin-daemon
          image: langgenius/dify-plugin-daemon:0.0.3-local
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: shared-config
            - secretRef:
                name: shared-secret
          env:
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: DB_PLUGIN_DATABASE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: PLUGIN_DAEMON_PORT
            - name: SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: PLUGIN_DAEMON_KEY
            - name: MAX_PLUGIN_PACKAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: PLUGIN_MAX_PACKAGE_SIZE
            - name: PPROF_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: PLUGIN_PPROF_ENABLED
            - name: DIFY_INNER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: PLUGIN_DIFY_INNER_API_URL
            - name: DIFY_INNER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: INNER_API_KEY_FOR_PLUGIN
            - name: PLUGIN_REMOTE_INSTALLING_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: EXPOSE_PLUGIN_DEBUGGING_HOST
            - name: PLUGIN_REMOTE_INSTALLING_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: EXPOSE_PLUGIN_DEBUGGING_PORT
            - name: PLUGIN_WORKING_PATH
              value: /app/storage
            - name: FORCE_VERIFYING_SIGNATURE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: FORCE_VERIFYING_SIGNATURE
          volumeMounts:
            - name: plugin-daemon-storage
              mountPath: /app/storage
      volumes:
        - name: plugin-daemon-storage
          persistentVolumeClaim:
            claimName: plugin-daemon-storage

---
apiVersion: v1
kind: Service
metadata:
  name: plugin-daemon
spec:
  ports:
    - port: 5002
      targetPort: 5002
      name: daemon-port
    - port: 5003
      targetPort: 5003
      name: debug-port
  selector:
    app: plugin-daemon
