apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-storage
spec:
  storageClassName: satahdd-replicated-cephfs-sc-01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
