apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: langgenius/dify-web:1.4.0
          ports:
            - containerPort: 3000
          env:
            - name: CONSOLE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CONSOLE_API_URL
            - name: APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: APP_API_URL
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: WEB_SENTRY_DSN
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: TEXT_GENERATION_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: TEXT_GENERATION_TIMEOUT_MS
            - name: CSP_WHITELIST
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CSP_WHITELIST
            - name: MARKETPLACE_API_URL
              value: "https://marketplace.dify.ai"
            - name: MARKETPLACE_URL
              value: "https://marketplace.dify.ai"
            - name: MARKETPLACE_ENABLED
            - name: TOP_K_MAX_VALUE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: TOP_K_MAX_VALUE
            - name: INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH
            - name: PM2_INSTANCES
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: PM2_INSTANCES

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: web
