apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: langgenius/dify-api:1.4.2
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: shared-config
            - secretRef:
                name: shared-secret
          env:
            - name: MODE
              value: "worker"
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: API_SENTRY_DSN
            - name: SENTRY_TRACES_SAMPLE_RATE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: API_SENTRY_TRACES_SAMPLE_RATE
            - name: SENTRY_PROFILES_SAMPLE_RATE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: API_SENTRY_PROFILES_SAMPLE_RATE
            - name: PLUGIN_MAX_PACKAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: PLUGIN_MAX_PACKAGE_SIZE
          volumeMounts:
            - name: storage
              mountPath: /app/api/storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: api-storage

---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: worker
