apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dify
resources:
  - namespace.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
  - redis.yaml
  - sandbox.yaml
  - ssrf_proxy.yaml
  - qdrant.yaml
  - ingress.yaml
configMapGenerator:
  - name: shared-config
    envs:
      - configmap.env
secretGenerator:
  - name: shared-secret
    envs:
      - secret.env
