apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: shared-config
    behavior: merge
    envs:
      - configmap.env

resources:
  - ../../base
  - secret.yaml
