apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: langgenius/dify-api:0.8.2
        envFrom:
        - configMapRef:
            name: shared-config
        - secretRef:
            name: shared-secrets
        env:
        - name: MODE
          value: "api"
        - name: DB_HOST
          value: "pg-cluster-rw.pg-cluster.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "dify"
        volumeMounts:
        - name: storage
          mountPath: /app/api/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: api-storage
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
  - host: api.yourdomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 5001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi