apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
      - name: sandbox
        image: langgenius/dify-sandbox:0.2.9
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: shared-secrets
              key: SANDBOX_API_KEY
        - name: GIN_MODE
          value: "release"
        - name: WORKER_TIMEOUT
          value: "15"
        - name: ENABLE_NETWORK
          value: "true"
        - name: HTTP_PROXY
          value: "http://ssrf_proxy:3128"
        - name: HTTPS_PROXY
          value: "http://ssrf_proxy:3128"
        - name: SANDBOX_PORT
          value: "8194"
        volumeMounts:
        - name: dependencies
          mountPath: /dependencies
      volumes:
      - name: dependencies
        persistentVolumeClaim:
          claimName: sandbox-dependencies
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox
spec:
  selector:
    app: sandbox
  ports:
    - protocol: TCP
      port: 8194
      targetPort: 8194
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-dependencies
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi