apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  DB_USERNAME: "dify-user"
  DB_PASSWORD: "dify-user"
  REDIS_PASSWORD: "difyai123456"
  CELERY_BROKER_URL: "redis://:difyai123456@redis:6379/1"
  QDRANT_URL: "http://qdrant:6333"
  QDRANT_API_KEY: "difyai123456"
  QDRANT_CLIENT_TIMEOUT: "20"
  QDRANT_GRPC_ENABLED: "false"
  QDRANT_GRPC_PORT: "6334"
  AZURE_OPENAI_KEY: "your-azure-openai-key"
  AZURE_OPENAI_ENDPOINT: "https://your-azure-openai-endpoint"