apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: langgenius/dify-web:0.8.2
        env:
        - name: CONSOLE_API_URL
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: CONSOLE_API_URL
        - name: APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: SERVICE_API_URL
        - name: SENTRY_DSN
          value: ""
        - name: NEXT_TELEMETRY_DISABLED
          value: "0"
        - name: TEXT_GENERATION_TIMEOUT_MS
          value: "60000"
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
spec:
  rules:
  - host: web.yourdomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 80