apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: langgenius/dify-api:0.8.2
        envFrom:
        - configMapRef:
            name: shared-config
        - secretRef:
            name: shared-secrets
        env:
        - name: MODE
          value: "worker"
        - name: DB_HOST
          value: "pg-cluster-rw.pg-cluster.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "dify"
        volumeMounts:
        - name: storage
          mountPath: /app/api/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: worker-storage
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi