apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: shared-config
    behavior: merge
    envs:
      - configmap.env
secretGenerator:
  - name: shared-secret
    envs:
      - secret.env
